apiVersion: metrics.keptn.sh/v1alpha1
kind: KeptnMetricsProvider
metadata:
  name: dynatrace
  namespace: simplenode-dev
spec:
  targetServer: "https://hci34192.live.dynatrace.com"
  secretKeyRef:
    name: dynatrace
    key: DT_TOKEN
