apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnEvaluationDefinition
metadata:
  name: evaluate-dependencies
  namespace: simplenode-dev
spec:
  objectives:
    - keptnMetricRef:
        name: available-cpus
        namespace: simplenode-dev
      evaluationTarget: ">4"
---
apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnEvaluationDefinition
metadata:
  name: evaluate-deployment
  namespace: simplenode-dev
spec:
# Evaluations can range across multiple objectives from different sources, e.g: Infra from Prometheus, SLOs from Dynatrace
  objectives:
    - keptnMetricRef:
        name: available-cpus
        namespace: simplenode-dev
      evaluationTarget: ">4"
    - keptnMetricRef:
        name: availability-slo
        namespace: simplenode-dev
      evaluationTarget: ">90"
